import { createTheme, ITheme } from '@fluentui/react';

export const SoftPinkTheme: ITheme = createTheme({
  palette: {
    themePrimary: '#ec4899',
    themeLighterAlt: '#fdf7fc',
    themeLighter: '#f7e1f0',
    themeLight: '#f0c7e1',
    themeTertiary: '#e194c6',
    themeSecondary: '#d368ae',
    themeDarkAlt: '#d4418a',
    themeDark: '#b3377a',
    themeDarker: '#84285a',
    neutralLighterAlt: '#fdf2f8',
    neutralLighter: '#fce7f3',
    neutralLight: '#f9a8d4',
    neutralQuaternaryAlt: '#f3e8ff',
    neutralQuaternary: '#e5e7eb',
    neutralTertiaryAlt: '#c1c1c1',
    neutralTertiary: '#a1a1aa',
    neutralSecondary: '#71717a',
    neutralPrimaryAlt: '#52525b',
    neutralPrimary: '#3f3f46',
    neutralDark: '#27272a',
    black: '#18181b',
    white: '#fdf2f8',
  },
  semanticColors: {
    bodyBackground: '#fdf2f8',
    bodyStandoutBackground: '#fce7f3',
    bodyFrameBackground: '#f9a8d4',
    bodyFrameDivider: '#ec4899',
    bodyText: '#be185d',
    bodyTextChecked: '#831843',
    bodySubtext: '#a21caf',
    bodyDivider: '#f9a8d4',
    
    disabledBackground: '#f3e8ff',
    disabledText: '#a1a1aa',
    disabledBodyText: '#a1a1aa',
    disabledSubtext: '#d1d5db',
    disabledBodySubtext: '#d1d5db',
    
    focusBorder: '#ec4899',
    variantBorder: '#f9a8d4',
    variantBorderHovered: '#ec4899',
    defaultStateBackground: '#fce7f3',
    
    errorText: '#dc2626',
    warningText: '#d97706',
    errorBackground: '#fef2f2',
    blockingBackground: '#fef2f2',
    warningBackground: '#fffbeb',
    warningHighlight: '#fef3c7',
    successBackground: '#f0fdf4',
    
    inputBorder: '#f9a8d4',
    inputBorderHovered: '#ec4899',
    inputBackground: '#fdf2f8',
    inputBackgroundChecked: '#ec4899',
    inputBackgroundCheckedHovered: '#d946ef',
    inputForegroundChecked: '#ffffff',
    inputFocusBorderAlt: '#be185d',
    smallInputBorder: '#f9a8d4',
    inputText: '#be185d',
    inputTextHovered: '#831843',
    inputPlaceholderText: '#a21caf',
    
    buttonBackground: '#fce7f3',
    buttonBackgroundChecked: '#ec4899',
    buttonBackgroundHovered: '#f9a8d4',
    buttonBackgroundCheckedHovered: '#d946ef',
    buttonBackgroundPressed: '#be185d',
    buttonBackgroundDisabled: '#f3e8ff',
    buttonBorder: '#f9a8d4',
    buttonText: '#be185d',
    buttonTextHovered: '#831843',
    buttonTextChecked: '#ffffff',
    buttonTextCheckedHovered: '#ffffff',
    buttonTextPressed: '#ffffff',
    buttonTextDisabled: '#a1a1aa',
    buttonBorderDisabled: '#e5e7eb',
    
    primaryButtonBackground: '#ec4899',
    primaryButtonBackgroundHovered: '#d946ef',
    primaryButtonBackgroundPressed: '#be185d',
    primaryButtonBackgroundDisabled: '#e5e7eb',
    primaryButtonBorder: 'transparent',
    primaryButtonText: '#ffffff',
    primaryButtonTextHovered: '#ffffff',
    primaryButtonTextPressed: '#ffffff',
    primaryButtonTextDisabled: '#a1a1aa',
    
    accentButtonBackground: '#ec4899',
    accentButtonText: '#ffffff',
    
    menuBackground: '#fdf2f8',
    menuDivider: '#f9a8d4',
    menuIcon: '#be185d',
    menuHeader: '#831843',
    menuItemBackgroundHovered: '#fce7f3',
    menuItemBackgroundPressed: '#f9a8d4',
    menuItemText: '#be185d',
    menuItemTextHovered: '#831843',
    
    listBackground: '#fdf2f8',
    listText: '#be185d',
    listItemBackgroundHovered: '#fce7f3',
    listItemBackgroundChecked: '#f9a8d4',
    listItemBackgroundCheckedHovered: '#ec4899',
    
    listHeaderBackgroundHovered: '#fce7f3',
    listHeaderBackgroundPressed: '#f9a8d4',
      actionLink: '#ec4899',
    actionLinkHovered: '#d946ef',
    link: '#ec4899',
    linkHovered: '#d946ef',
  },
});
